import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import AuthProvider from "@/auth/components/AuthProvider";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="es">
        <body className={roboto.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
